// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	v1 "github.com/kinneko-de/api-contract/golang/kinnekode/restaurant/document/v1"
	mock "github.com/stretchr/testify/mock"
)

// DocumentServiceGateway is an autogenerated mock type for the DocumentServiceGateway type
type DocumentServiceGateway struct {
	mock.Mock
}

// CreateDocumentServiceClient provides a mock function with given fields:
func (_m *DocumentServiceGateway) CreateDocumentServiceClient() (v1.DocumentServiceClient, error) {
	ret := _m.Called()

	var r0 v1.DocumentServiceClient
	var r1 error
	if rf, ok := ret.Get(0).(func() (v1.DocumentServiceClient, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() v1.DocumentServiceClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.DocumentServiceClient)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDocumentServiceGateway creates a new instance of DocumentServiceGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDocumentServiceGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *DocumentServiceGateway {
	mock := &DocumentServiceGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
