// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/kinneko-de/api-contract/golang/kinnekode/restaurant/document/v1"
)

// DocumentServiceClient is an autogenerated mock type for the DocumentServiceClient type
type DocumentServiceClient struct {
	mock.Mock
}

type DocumentServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *DocumentServiceClient) EXPECT() *DocumentServiceClient_Expecter {
	return &DocumentServiceClient_Expecter{mock: &_m.Mock}
}

// GeneratePreview provides a mock function with given fields: ctx, in, opts
func (_m *DocumentServiceClient) GeneratePreview(ctx context.Context, in *v1.GeneratePreviewRequest, opts ...grpc.CallOption) (v1.DocumentService_GeneratePreviewClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 v1.DocumentService_GeneratePreviewClient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.GeneratePreviewRequest, ...grpc.CallOption) (v1.DocumentService_GeneratePreviewClient, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.GeneratePreviewRequest, ...grpc.CallOption) v1.DocumentService_GeneratePreviewClient); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.DocumentService_GeneratePreviewClient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.GeneratePreviewRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DocumentServiceClient_GeneratePreview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GeneratePreview'
type DocumentServiceClient_GeneratePreview_Call struct {
	*mock.Call
}

// GeneratePreview is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.GeneratePreviewRequest
//   - opts ...grpc.CallOption
func (_e *DocumentServiceClient_Expecter) GeneratePreview(ctx interface{}, in interface{}, opts ...interface{}) *DocumentServiceClient_GeneratePreview_Call {
	return &DocumentServiceClient_GeneratePreview_Call{Call: _e.mock.On("GeneratePreview",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *DocumentServiceClient_GeneratePreview_Call) Run(run func(ctx context.Context, in *v1.GeneratePreviewRequest, opts ...grpc.CallOption)) *DocumentServiceClient_GeneratePreview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v1.GeneratePreviewRequest), variadicArgs...)
	})
	return _c
}

func (_c *DocumentServiceClient_GeneratePreview_Call) Return(_a0 v1.DocumentService_GeneratePreviewClient, _a1 error) *DocumentServiceClient_GeneratePreview_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DocumentServiceClient_GeneratePreview_Call) RunAndReturn(run func(context.Context, *v1.GeneratePreviewRequest, ...grpc.CallOption) (v1.DocumentService_GeneratePreviewClient, error)) *DocumentServiceClient_GeneratePreview_Call {
	_c.Call.Return(run)
	return _c
}

// NewDocumentServiceClient creates a new instance of DocumentServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDocumentServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *DocumentServiceClient {
	mock := &DocumentServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
