apiVersion: v1
kind: Service
metadata:
  name: document-design-gateway
  namespace: restaurant
spec:
  selector:
    app: document-design-gateway
  type: LoadBalancer # Need metallb addon to be enabled in microk8s
  ports:
  - name: http
    port: 80
    targetPort: 8080