apiVersion: v1
kind: Service
metadata:
  name: document-design-gateway
  namespace: restaurant
  annotations:
    # Add Istio sidecar injection annotation
    # to automatically inject the sidecar proxy
    # into the pod when it's created
    sidecar.istio.io/inject: "true"
spec:
  selector:
    app: document-design-gateway
  ports:
  - name: grpc
    port: 3110
    targetPort: 3110
  # Add Istio specific configuration
  # to enable Istio to route traffic to the service
  # and to configure Istio's load balancing algorithm
  # for the service
  # trafficPolicy:
  #  loadBalancer:
  #    simple: ROUND_ROBIN