apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: restaurant-ingress
  namespace: restaurant
spec:
  gateways:
  - istio-system/ingressgateway
  hosts:
  - "*"
  http:
  - route:
      - destination:
          host: document-design-gateway.restaurant.svc.cluster.local
          port:
            number: 80
  #- match:
  #  - uri:
  #      prefix: /restaurant/document
  #    retries: # retry policy deactivated because otherwise 503 are retried with the same state.. but only when state is there but retries only on 503.. not on 500 => metric!!
  #      attempts: 0
  #  route:
  #  - destination:
  #      host: document-design-gateway.restaurant.svc.cluster.local
  #      port:
  #        number: 80
