apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  auth:
    strategy: anonymous
  server:
    web_root: "/kiali"
  external_services:
    prometheus:
      url: 'http://prometheus-operated.observability:9090'
    grafana:
      enabled: false
      in_cluster_url: 'http://kube-prom-stack-grafana.observability:80'
      url: 'http://localhost:3000' # not availabe without port-forwarding
    tracing:
      enabled: false #configuration is wrong
      url: 'http://tempo.observability.svc:16686/'
      provider: "tempo"
      use_grpc: true